services:
  terramar.new_relic.driver:
    public: false
    class: Terramar\Bundle\NewRelicBundle\Driver\DefaultDriver

  terramar.new_relic.subscriber.request_lifecycle:
    class: Terramar\Bundle\NewRelicBundle\Subscriber\RequestLifecycleSubscriber
    arguments: [ @terramar.new_relic.driver ]
    tags:
      - { name: kernel.event_subscriber }
  terramar.new_relic.subscriber.console_lifecycle:
    class: Terramar\Bundle\NewRelicBundle\Subscriber\ConsoleLifecycleSubscriber
    arguments: [ @terramar.new_relic.driver ]
    tags:
      - { name: kernel.event_subscriber }
